### PR TITLE
new version of SetUnit.jl, included mass and length units as sample

### PR DESCRIPTION
**Pull request by lllx125**
I made the new SetUnit.jl, with new structures for units. 
the function setunits() is not implemented but I wrote tests at the bottom and its results. The function and the units worked as desired. Once the file for global variable need to be declared is created, it would be easy to include other units and implement the body of the function setunits().

### CODE REVIEW

**Comment by lllx125** [comment]
I added initialization for variables in global.jl

**Comment by lllx125** [comment]
I think it would be better to initialize variables in global.jl to 0 because I will be creating them in setunits() anyway. 
Also, there is 1 line that r_p = r_e * m_electron / m_proton, 
if m_proton =0 there will be runtime error

**Comment by rot4te** [comment]
Looks really good. My last quibble (which I should have mentioned earlier) is that your metric-prefix changing functions (k(), M(), etc.) aren't very informative... naming them the 4 or five character prefix name (kilo(), Mega(), etc.) might be better.

**Comment by rot4te** [comment]
I'm also curious as to why your global mass unit is amu, as opposed to eV/c^2, which is what all the base masses are in.

**Comment by lllx125** [comment]
> I'm also curious as to why your global mass unit is amu, as opposed to eV/c^2, which is what all the base masses are in.
> Looks really good. My last quibble (which I should have mentioned earlier) is that your metric-prefix changing functions (k(), M(), etc.) aren't very informative... naming them the 4 or five character prefix name (kilo(), Mega(), etc.) might be better.

I can change both of these. I thought the isotope masses were in amu, and that is the majority of the data. Should setunits() also convert the isotope data?

**Comment by DavidSagan** [comment]
Unless there was a good reason not to, I would favor having isotope masses in AMU since it makes it easier for someone doing a deep dive in the code to compare against the literature.

**Pull request closed without merging**
