### PR TITLE
Use Macros to define new variables

### PR DESCRIPTION
**Pull request by lllx125**
Now setunits works as a macro that accepts a unit system and *reassigns* constants exported from AtomicAndPhysicalConstants with value in the proper unit.

Example: 
@setunits MKS

This is because @setunits is called in __init__(), so I can't define constants in a function. However, this makes the constants type unstable. 

The code should work properly if we ignore typing.

### CODE REVIEW

**Review by DavidSagan — APPROVED** [review]
Fixes problem with AcceleratorLattice.

**Comment by DavidSagan** [comment]
I am getting the error for atoms:
```
julia> Species("He")
ERROR: type AtomicSpecies has no field mass_in_amu
```

**Comment by mattsignorelli** [comment]
We can’t ignore the types or reassign constants, that is very dangerous and does not work. Instead @setunits should be called in the global scope of the package using AAPC, not in init. Then this will work just fine.Sent from my iPhoneOn Nov 19, 2024, at 10:16 PM, David Sagan ***@***.***> wrote:﻿
I am getting the error for atoms:
julia> Species("He")
ERROR: type AtomicSpecies has no field mass_in_amu

**Comment by DavidSagan** [comment]
`chargeof` is broken:
```
julia> f = Species("electron")
Species("electron", -1 e, 0.51099895069 MeV c⁻², 0.5 ħ, -9.2847646917e-24 J T⁻¹, 0)

julia> chargeof(f)
ERROR: DimensionError: e and MeV c⁻² are not dimensionally compatible.
Stacktrace:
 [1] #s103#141
   @ ~/.julia/packages/Unitful/GYzMo/src/conversion.jl:7 [inlined]
 [2] var"#s103#141"(::Any, s::Any, t::Any)
   @ Unitful ./none:0
 [3] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
   @ Core ./boot.jl:707
 [4] uconvert(a::Unitful.FreeUnits{(e,), 𝐈 𝐓, nothing}, x::Quantity{Float64, 𝐌, Unitful.FreeUnits{(c⁻², MeV), 𝐌, nothing}})
   @ Unitful ~/.julia/packages/Unitful/GYzMo/src/conversion.jl:72
 [5] (::AcceleratorLattice.var"#6#8"{Unitful.FreeUnits{(e,), 𝐈 𝐓, nothing}})(species::Species)
   @ AcceleratorLattice ~/.julia/dev/AtomicAndPhysicalConstants/src/set_units.jl:140
 [6] top-level scope
   @ REPL[6]:1
```

**Comment by lllx125** [comment]
Allow macro to be set with keyword parameters

**Comment by DavidSagan** [comment]
@lllx125 With the latest code I get:
```
julia> using AtomicAndPhysicalConstants
Precompiling AtomicAndPhysicalConstants...
Info Given AtomicAndPhysicalConstants was explicitly requested, output will be shown live 
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
... And lots more lines like this...

julia> f = Species("electron")
Species("electron", -1 e, 0.51099895069 MeV c⁻², 0.5 ħ, -9.2847646917e-24 J T⁻¹, 0)

julia> chargeof(f)
ERROR: UndefVarError: `chargeof` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

**Review by DavidSagan — CHANGES_REQUESTED** [review]
With the latest code I get:
```
julia> using AtomicAndPhysicalConstants
Precompiling AtomicAndPhysicalConstants...
Info Given AtomicAndPhysicalConstants was explicitly requested, output will be shown live 
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
┌ Warning: Symbol ħ was found in multiple registered unit modules.
│ We will use the one from AtomicAndPhysicalConstants.NewUnits.
└ @ Unitful ~/.julia/packages/Unitful/GYzMo/src/user.jl:715
... And lots more lines like this...

julia> f = Species("electron")
Species("electron", -1 e, 0.51099895069 MeV c⁻², 0.5 ħ, -9.2847646917e-24 J T⁻¹, 0)

julia> chargeof(f)
ERROR: UndefVarError: `chargeof` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

Also if a `"null"` species can be defined that would be helpful.

**Comment by DavidSagan** [comment]
@mattsignorelli Yes I had forgot that. The package should be configured to throw an error message in this case that tells the user they need to use `@AAPCdef`.

**Comment by mattsignorelli** [comment]
> @mattsignorelli Yes I had forgot that. The package should be configured to throw an error message in this case that tells the user they need to use `@AAPCdef`.

That wouldn't work because `massof` and `chargeof` must not exist anywhere before calling the macro.

**Comment by DavidSagan** [comment]
@mattsignorelli Can dummy functions be defined initially with the `use` statement to throw an error?

**Comment by DavidSagan** [comment]
One more point: The default for `@AAPCdef` should be that `C_LIGHT`, `chargeof`, etc be numbers and not have units.

**Comment by mattsignorelli** [comment]
> @mattsignorelli Can dummy functions be defined initially with the `use` statement to throw an error?

This is dangerous because then every package using AAPC will need to do type piracy on these functions

**Comment by mattsignorelli** [comment]
> function __init__()
>     @AAPCdef;
>   end

This is the problem, `@APCdef`  should not be called in `__init__` but in the global scope of accelerator lattice.

However @lllx125  the macro should just define `const`, not `global const`

**Comment by DavidSagan** [comment]
I removed the `__init__` from AcceleratorLattice and the `global` from APC and the   `global const declaration` problem went away.

**Comment by DavidSagan** [comment]
@lllx125 You need to change `export @AAPCdef` to `export @APCdef`

**Review by mattsignorelli — APPROVED** [review]

**Review by DavidSagan — APPROVED** [review]

**Pull request merged**
